python_whats:
  build: ./python_whats/
  
web:
  restart: always
  build: ./web
  expose:
    - "5000"
  ports:
    - "5000:5000"
  links:
    - redis
    - mongo
  volumes:
    - /home/dkr/porwhats/web:/app/
    - /home/dkr/porwhats/logs:/app/logs
    - /home/dkr/porwhats/web/static/:/app/static
    - /home/dkr/porwhats/uploads/:/app/static/uploads
    - /home/dkr/porwhats/web/requirements.txt:/app/web/requirements.txt
    - /home/dkr/porwhats/web/docker-entrypoint.sh:/app/web/docker-entrypoint.sh
    - /home/dkr/porwhats/configurations/app/app.ini:/etc/supervisor/app.ini
    - /home/dkr/porwhats/configurations/app/downloader.ini:/etc/supervisor/downloader.ini
    - /home/dkr/porwhats/configurations/supervisor/supervisord.conf:/etc/supervisord.conf
  env_file: .env
  working_dir: /app
  entrypoint: ./docker-entrypoint.sh

nginx:
  restart: always
  build: ./nginx/
  ports:
    - "80:80"
  volumes:
    - /home/dkr/porwhats/web/static/:/www/static
    - /home/dkr/porwhats/uploads/:/app/static/uploads
    - /etc/letsencrypt/live/porwhats.com/fullchain.pem:/etc/letsencrypt/live/porwhats.com/fullchain.pem
    - /etc/letsencrypt/live/porwhats.com/privkey.pem:/etc/letsencrypt/live/porwhats.com/privkey.pem
  volumes_from:
    - web
  links:
    - web:web

mongo:
  image: mongo:latest
  volumes:  
    - /home/dkr/data/db:/data/db

redis:
  image: redis:3.0.5
  ports:
    - "0.0.0.0:6379:6379"  